{% set name = "snowmeta" %}
{% set version = "0.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f83f1bf68024b2bcfe706e806023114ad2d015b7d224f63b7b646b9f95ca890d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - snowflake-snowpark-python >=1.0.0
    - pandas >=1.3.0
    - pyyaml >=6.0

test:
  imports:
    - snowmeta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marvinkobit/snow-meta
  summary: 'Snowmeta: a metadata-driven ingestion framework for Snowflake.'
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/marvinkobit/snow-meta

extra:
  recipe-maintainers:
    - marvinkobit
