{% set name = "snowmeta" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/snowmeta-{{ version }}.tar.gz
  sha256: f83f1bf68024b2bcfe706e806023114ad2d015b7d224f63b7b646b9f95ca890d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - snowflake-snowpark-python >=1.0.0
    - pandas >=1.3.0
    - pyyaml >=6.0

test:
  imports:
    - snowmeta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marvinkobit/snow-meta
  summary: 'Snowmeta: a metadata-driven ingestion framework for Snowflake.'
  dev_url: https://github.com/marvinkobit/snow-meta
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maeruf
