# Snowflake Streamlit environment.yml file
# This file is used when deploying to Streamlit in Snowflake

name: snowmeta_ui
channels:
  - snowflake
  - conda-forge
dependencies:
  - python=3.10
  - streamlit>=1.28.0
  - snowflake-snowpark-python>=1.11.0
  - pandas>=2.0.0

